/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#6ffbbe",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-variant": "#e0e3e5",
        "secondary-fixed": "#dbe1ff",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed": "#d8e2ff",
        "outline": "#75777f",
        "secondary-container": "#316bf3",
        "secondary": "#0051d5",
        "on-surface-variant": "#44474e",
        "primary-container": "#1a2b4b",
        "outline-variant": "#c5c6cf",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#364768",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#b6c6ef",
        "on-primary-container": "#8293b8",
        "on-primary": "#ffffff",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container": "#eceef0",
        "surface-tint": "#4e5e81",
        "inverse-primary": "#b6c6ef",
        "on-primary-fixed": "#081b3a",
        "on-secondary-container": "#fefcff",
        "tertiary": "#001c10",
        "on-surface": "#191c1e",
        "on-secondary-fixed": "#00174b",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "tertiary-container": "#003320",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary-container": "#00a774",
        "on-tertiary-fixed": "#002113",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#003ea8",
        "primary": "#031635"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-margin": "24px",
        "gutter": "16px",
        "sm": "8px",
        "md": "16px",
        "xs": "4px",
        "lg": "24px",
        "xl": "32px",
        "base": "4px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "title-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "code-md": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "title-md": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
