import React, { useState } from 'react';
import { initialActionItems } from '../services/mockData';
import { ActionItemCard } from '../components/ActionItemCard';
import { ActionItem } from '../types';

export const ActionsPage: React.FC = () => {
  const [items, setItems] = useState<ActionItem[]>(initialActionItems);
  const [filter, setFilter] = useState<'All' | 'Pending' | 'In Progress' | 'Completed'>('All');

  const handleToggleComplete = (id: string, currentStatus: string) => {
    setItems((prev) =>
      prev.map((item) =>
        item.id === id
          ? { ...item, status: currentStatus === 'Completed' ? 'Pending' : 'Completed' }
          : item
      )
    );
  };

  const filteredItems = items.filter(
    (item) => filter === 'All' || item.status === filter
  );

  return (
    <div className="space-y-lg">
      <div className="flex flex-wrap justify-between items-center gap-md pb-sm border-b border-outline-variant">
        <div>
          <h2 className="font-headline-lg text-headline-lg font-bold text-primary">
            Action Center & Recommended Tasks
          </h2>
          <p className="font-body-md text-body-md text-on-surface-variant mt-xs">
            Prioritized action checklist generated by MSME AI to maximize compliance health and opportunity capture.
          </p>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center gap-xs bg-surface-container-lowest p-sm rounded-xl border border-outline-variant overflow-x-auto">
        {(['All', 'Pending', 'In Progress', 'Completed'] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setFilter(tab)}
            className={`px-md py-1.5 rounded-lg font-label-md text-xs font-semibold whitespace-nowrap transition-all ${
              filter === tab
                ? 'bg-secondary text-on-secondary shadow-xs'
                : 'text-on-surface-variant hover:bg-surface-container-high'
            }`}
          >
            {tab} Actions ({items.filter((i) => tab === 'All' || i.status === tab).length})
          </button>
        ))}
      </div>

      {/* Action Items List */}
      <div className="space-y-md">
        {filteredItems.map((item) => (
          <ActionItemCard key={item.id} item={item} onToggleComplete={handleToggleComplete} />
        ))}
      </div>
    </div>
  );
};
